Update Trigger in sequence.yml
Signed-off-by: REIJI007 <miyajimareji007@gmail.com>

diff --git a/.github/workflows/Trigger in sequence.yml b/.github/workflows/Trigger in sequence.yml
--- a/.github/workflows/Trigger in sequence.yml
+++ b/.github/workflows/Trigger in sequence.yml
@@ -48,9 +48,51 @@ jobs:
           # 等待90秒
           sleep 90
 
+  # 触发 Rename and Push File 工作流
+  rename_and_push_file:
+    needs: trigger_adblock_rule_generator_quantumult_list
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      - name: Trigger and verify Rename and Push File
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Rename and Push File.yml"
+          ref="main"
+          # 触发工作流
+          response=$(curl -X POST -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Quantumult/actions/workflows/$workflow_id/dispatches" \
+            -d "{\"ref\":\"$ref\"}")
+          echo "Triggered workflow $workflow_id: $response"
+
+          # 验证工作流成功触发和完成
+          while : ; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Quantumult/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete..."
+              sleep 30
+            fi
+          done
+
+          # 等待90秒
+          sleep 90
+
   # 触发 Release_ADblock_Files 工作流
   release_adblock_files:
-    needs: trigger_adblock_rule_generator_quantumult_list
+    needs: rename_and_push_file
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
