Update Trigger in sequence.yml
Signed-off-by: REIJI007 <miyajimareji007@gmail.com>

diff --git a/.github/workflows/Trigger in sequence.yml b/.github/workflows/Trigger in sequence.yml
--- a/.github/workflows/Trigger in sequence.yml
+++ b/.github/workflows/Trigger in sequence.yml
@@ -71,15 +71,81 @@ jobs:
           echo "Waiting for 90 seconds before starting the next workflow..."
           sleep 90
 
-  trigger_url_rewrite_list:
+  trigger_rename_and_push:
     runs-on: ubuntu-latest
     needs: trigger_quantumult_list
     steps:
-      - name: Trigger Run_AdBlock_Rule_Generator_URL_Rewrite_LIST
+      - name: Trigger Rename_and_Push_File
         env:
           TOKEN: ${{ secrets.TOKEN }}
         run: |
-          workflow_id="Run_AdBlock_Rule_Generator_URL_Rewrite_LIST.yml"
+          workflow_id="Rename_and_Push_File.yml"
+          ref="main"
+          url="https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Quantumult/actions/workflows/$workflow_id/dispatches"
+          
+          echo "Triggering workflow at $url"
+
+          max_retries=5
+          for ((i=0; i<max_retries; i++)); do
+            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "$url" \
+              -d "{\"ref\":\"$ref\"}")
+            
+            if [[ "$response" == "204" ]]; then
+              echo "Successfully triggered workflow $workflow_id"
+              break
+            else
+              echo "Failed to trigger workflow $workflow_id, attempt $((i+1))/$max_retries"
+              sleep 10
+            fi
+
+            if [[ $i -eq $((max_retries-1)) ]]; then
+              echo "Failed to trigger workflow after $max_retries attempts."
+              exit 1
+            fi
+          done
+
+          # 验证工作流成功触发
+          retries=0
+          max_retries=20  # 最大重试次数
+          while [[ $retries -lt $max_retries ]]; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Quantumult/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete... ($((retries+1))/$max_retries)"
+              retries=$((retries+1))
+              sleep 30
+            fi
+
+            if [[ $retries -eq $max_retries ]]; then
+              echo "Workflow did not complete successfully after $max_retries attempts."
+              exit 1
+            fi
+          done
+
+          # 等待90秒后开始下一个工作流
+          echo "Waiting for 90 seconds before starting the next workflow..."
+          sleep 90
+
+  trigger_release_adblock_files:
+    runs-on: ubuntu-latest
+    needs: trigger_rename_and_push
+    steps:
+      - name: Trigger Release_ADblock_Files
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Release_ADblock_Files.yml"
           ref="main"
           url="https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Quantumult/actions/workflows/$workflow_id/dispatches"
           
